name: "Check for newer chainguard image versions"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  digest-update-chainguard-21:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: navikt/digestabot@e4b413f1eed3c97f7fd4ffa1d05204de9944d0a9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          team: k9saksbehandling
          working-dir: "/java/chainguard-21"

  digest-update-chainguard-25:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: navikt/digestabot@e4b413f1eed3c97f7fd4ffa1d05204de9944d0a9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          team: k9saksbehandling
          working-dir: "/java/chainguard-25"
