name: Build and deploy

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'
  schedule:
    - cron: '23 23 * * 2'
  workflow_dispatch:

jobs:
  build-java:
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        version: [ '21', '23' ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: java
          platforms: linux/amd64,linux/arm64
          build-args: BASE_IMAGE=eclipse-temurin:${{matrix.version}}-jre-alpine
          pull: true
          push: ${{ github.ref_name == 'master' }}
          tags: ghcr.io/${{ github.repository }}/java:${{matrix.version}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  #trivy-java21:
  #  needs: [build-java]
  #  permissions:
  #    actions: read
  #    contents: read
  #    security-events: write
  #  strategy:
  #    matrix:
  #      version: [ '21', '23' ]
  #  name: Trivy
  #  uses: navikt/sif-gha-workflows/.github/workflows/trivy.yml@main
  #  with:
  #    image: ghcr.io/${{ github.repository }}/java:${{matrix.version}}
  #    team: k9saksbehandling
  #  secrets: inherit
  #