name: Build and push

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'
  schedule:
    - cron: '23 23 * * 2'
  workflow_dispatch:

jobs:
  build-java:
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        version: [ '21', '23' ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4
      - name: Extract timesttamp
        id: timestamp
        run: |
          echo "TIMESTAMP=$(date -u +'%Y.%m.%d.%H%MZ')" >> $GITHUB_ENV
          echo "DATE_HOUR=$(date -u +'%Y%m%d%HZ')" >> $GITHUB_ENV
      - name: Bygg og push docker image
        id: docker-build
        uses: navikt/sif-gha-workflows/.github/actions/maven/build-push-docker-image@main # ratchet:exclude
        with:
          docker_context: java
          dockerfile: java/${{matrix.version}}/Dockerfile
          image_suffix: /java-${{matrix.version}}
          build-args: |
            CACHEBUST=${{ env.DATE_HOUR }}
          build-version: ${{ env.TIMESTAMP }}
          push-image: ${{ github.ref_name == github.event.repository.default_branch}}
          secrets: inherit