name: Trivy vulnerabilities scanning of dependencies
on:
  schedule:
    - cron:  '20 21 * * 6'
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/trivy.yml'

jobs:
  trivy:
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      matrix:
        version: [ '21', '23' ]
    name: Trivy
    uses: navikt/sif-gha-workflows/.github/workflows/trivy.yml@main
    with:
      image: ghcr.io/${{ github.repository }}/java:${{matrix.version}}
      team: k9saksbehandling
    secrets: inherit
